using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Datalogics.PdfWebApi.ProvisionClient
{
    public enum Country
    {
        Afghanistan,
        Ãland_Islands,
        Albania,
        Algeria,
        American_Samoa,
        Andorra,
        Angola,
        Anguilla,
        Antarctica,
        Antigua_and_Barbuda,
        Argentina,
        Armenia,
        Aruba,
        Ascension_Island,
        Australia,
        Austria,
        Azerbaijan,
        Bahamas,
        Bahrain,
        Bangladesh,
        Barbados,
        Belarus,
        Belgium,
        Belize,
        Benin,
        Bermuda,
        Bhutan,
        Bolivia,
        Bosnia_and_Herzegovina,
        Botswana,
        Bouvet_Island,
        Brazil,
        British_Antarctic_Territory,
        British_Indian_Ocean_Territory,
        British_Virgin_Islands,
        Brunei,
        Bulgaria,
        Burkina_Faso,
        Burundi,
        Cambodia,
        Cameroon,
        Canada,
        Canary_Islands,
        Canton_and_Enderbury_Islands,
        Cape_Verde,
        Cayman_Islands,
        Central_African_Republic,
        Ceuta_and_Melilla,
        Chad,
        Chile,
        China,
        Christmas_Island,
        Clipperton_Island,
        Cocos_Keeling_Islands,
        Colombia,
        Comoros,
        Congo_Brazzaville,
        Congo_Kinshasa,
        Cook_Islands,
        Costa_Rica,
        Cote_d_Ivoire,
        Croatia,
        Cuba,
        Cyprus,
        Czech_Republic,
        Denmark,
        Diego_Garcia,
        Djibouti,
        Dominica,
        Dominican_Republic,
        Dronning_Maud_Land,
        Ecuador,
        Egypt,
        El_Salvador,
        Equatorial_Guinea,
        Eritrea,
        Estonia,
        Ethiopia,
        European_Union,
        Falkland_Islands,
        Faroe_Islands,
        Fiji,
        Finland,
        France,
        French_Guiana,
        French_Polynesia,
        French_Southern_and_Antarctic_Territories,
        French_Southern_Territories,
        Gabon,
        Gambia,
        Georgia,
        Germany,
        Ghana,
        Gibraltar,
        Greece,
        Greenland,
        Grenada,
        Guadeloupe,
        Guam,
        Guatemala,
        Guernsey,
        Guinea,
        Guinea_Bissau,
        Guyana,
        Haiti,
        Heard_Island_and_McDonald_Islands,
        Honduras,
        Hong_Kong_SAR_China,
        Hungary,
        Iceland,
        India,
        Indonesia,
        Iran,
        Iraq,
        Ireland,
        Isle_of_Man,
        Israel,
        Italy,
        Jamaica,
        Japan,
        Jersey,
        Johnston_Island,
        Jordan,
        Kazakhstan,
        Kenya,
        Kiribati,
        Kuwait,
        Kyrgyzstan,
        Laos,
        Latvia,
        Lebanon,
        Lesotho,
        Liberia,
        Libya,
        Liechtenstein,
        Lithuania,
        Luxembourg,
        Macau_SAR_China,
        Macedonia,
        Madagascar,
        Malawi,
        Malaysia,
        Maldives,
        Mali,
        Malta,
        Marshall_Islands,
        Martinique,
        Mauritania,
        Mauritius,
        Mayotte,
        Metropolitan_France,
        Mexico,
        Micronesia,
        Midway_Islands,
        Moldova,
        Monaco,
        Mongolia,
        Montenegro,
        Montserrat,
        Morocco,
        Mozambique,
        Myanmar_Burma,
        Namibia,
        Nauru,
        Nepal,
        Netherlands,
        Netherlands_Antilles,
        New_Caledonia,
        New_Zealand,
        Nicaragua,
        Niger,
        Nigeria,
        Niue,
        Norfolk_Island,
        North_Korea,
        Northern_Mariana_Islands,
        Norway,
        Oman,
        Outlying_Oceania,
        Pacific_Islands_Trust_Territory,
        Pakistan,
        Palau,
        Palestinian_Territories,
        Panama,
        Panama_Canal_Zone,
        Papua_New_Guinea,
        Paraguay,
        Peoples_Democratic_Republic_of_Yemen,
        Peru,
        Philippines,
        Pitcairn_Islands,
        Poland,
        Portugal,
        Puerto_Rico,
        Qatar,
        Reunion,
        Romania,
        Russia,
        Rwanda,
        Saint_Barthelemy,
        Saint_Helena,
        Saint_Kitts_and_Nevis,
        Saint_Lucia,
        Saint_Martin,
        Saint_Pierre_and_Miquelon,
        Saint_Vincent_and_the_Grenadines,
        Samoa,
        San_Marino,
        Sao_Tome_and_Principe,
        Saudi_Arabia,
        Senegal,
        Serbia,
        Serbia_and_Montenegro,
        Seychelles,
        Sierra_Leone,
        Singapore,
        Slovakia,
        Slovenia,
        Solomon_Islands,
        Somalia,
        South_Africa,
        South_Georgia_and_the_South_Sandwich_Islands,
        South_Korea,
        Spain,
        Sri_Lanka,
        Sudan,
        Suriname,
        Svalbard_and_Jan_Mayen,
        Swaziland,
        Sweden,
        Switzerland,
        Syria,
        Taiwan,
        Tajikistan,
        Tanzania,
        Thailand,
        Timor_Leste,
        Togo,
        Tokelau,
        Tonga,
        Trinidad_and_Tobago,
        Tristan_da_Cunha,
        Tunisia,
        Turkey,
        Turkmenistan,
        Turks_and_Caicos_Islands,
        Tuvalu,
        US_Minor_Outlying_Islands,
        US_Miscellaneous_Pacific_Islands,
        US_Virgin_Islands,
        Uganda,
        Ukraine,
        United_Arab_Emirates,
        United_Kingdom,
        United_States,
        Uruguay,
        Uzbekistan,
        Vanuatu,
        Vatican_City,
        Venezuela,
        Vietnam,
        Wake_Island,
        Wallis_and_Futuna,
        Western_Sahara,
        Yemen,
        Zambia,
        Zimbabwe
    };

    public static class CountryExtensions
    {
        public static string ToDisplayString(this Country country)
        {
            string[] countries = new string[] 
            {
                "Afghanistan",
                "Åland Islands",
                "Albania",
                "Algeria",
                "American Samoa",
                "Andorra",
                "Angola",
                "Anguilla",
                "Antarctica",
                "Antigua and Barbuda",
                "Argentina",
                "Armenia",
                "Aruba",
                "Ascension Island",
                "Australia",
                "Austria",
                "Azerbaijan",
                "Bahamas",
                "Bahrain",
                "Bangladesh",
                "Barbados",
                "Belarus",
                "Belgium",
                "Belize",
                "Benin",
                "Bermuda",
                "Bhutan",
                "Bolivia",
                "Bosnia and Herzegovina",
                "Botswana",
                "Bouvet Island",
                "Brazil",
                "British Antarctic Territory",
                "British Indian Ocean Territory",
                "British Virgin Islands",
                "Brunei",
                "Bulgaria",
                "Burkina Faso",
                "Burundi",
                "Cambodia",
                "Cameroon",
                "Canada",
                "Canary Islands",
                "Canton and Enderbury Islands",
                "Cape Verde",
                "Cayman Islands",
                "Central African Republic",
                "Ceuta and Melilla",
                "Chad",
                "Chile",
                "China",
                "Christmas Island",
                "Clipperton Island",
                "Cocos [Keeling] Islands",
                "Colombia",
                "Comoros",
                "Congo - Brazzaville",
                "Congo - Kinshasa",
                "Cook Islands",
                "Costa Rica",
                "Côte d'Ivoire",
                "Croatia",
                "Cuba",
                "Cyprus",
                "Czech Republic",
                "Denmark",
                "Diego Garcia",
                "Djibouti",
                "Dominica",
                "Dominican Republic",
                "Dronning Maud Land",
                "Ecuador",
                "Egypt",
                "El Salvador",
                "Equatorial Guinea",
                "Eritrea",
                "Estonia",
                "Ethiopia",
                "European Union",
                "Falkland Islands",
                "Faroe Islands",
                "Fiji",
                "Finland",
                "France",
                "French Guiana",
                "French Polynesia",
                "French Southern and Antarctic Territories",
                "French Southern Territories",
                "Gabon",
                "Gambia",
                "Georgia",
                "Germany",
                "Ghana",
                "Gibraltar",
                "Greece",
                "Greenland",
                "Grenada",
                "Guadeloupe",
                "Guam",
                "Guatemala",
                "Guernsey",
                "Guinea",
                "Guinea-Bissau",
                "Guyana",
                "Haiti",
                "Heard Island and McDonald Islands",
                "Honduras",
                "Hong Kong SAR China",
                "Hungary",
                "Iceland",
                "India",
                "Indonesia",
                "Iran",
                "Iraq",
                "Ireland",
                "Isle of Man",
                "Israel",
                "Italy",
                "Jamaica",
                "Japan",
                "Jersey",
                "Johnston Island",
                "Jordan",
                "Kazakhstan",
                "Kenya",
                "Kiribati",
                "Kuwait",
                "Kyrgyzstan",
                "Laos",
                "Latvia",
                "Lebanon",
                "Lesotho",
                "Liberia",
                "Libya",
                "Liechtenstein",
                "Lithuania",
                "Luxembourg",
                "Macau SAR China",
                "Macedonia",
                "Madagascar",
                "Malawi",
                "Malaysia",
                "Maldives",
                "Mali",
                "Malta",
                "Marshall Islands",
                "Martinique",
                "Mauritania",
                "Mauritius",
                "Mayotte",
                "Metropolitan France",
                "Mexico",
                "Micronesia",
                "Midway Islands",
                "Moldova",
                "Monaco",
                "Mongolia",
                "Montenegro",
                "Montserrat",
                "Morocco",
                "Mozambique",
                "Myanmar [Burma]",
                "Namibia",
                "Nauru",
                "Nepal",
                "Netherlands",
                "Netherlands Antilles",
                "New Caledonia",
                "New Zealand",
                "Nicaragua",
                "Niger",
                "Nigeria",
                "Niue",
                "Norfolk Island",
                "North Korea",
                "Northern Mariana Islands",
                "Norway",
                "Oman",
                "Outlying Oceania",
                "Pacific Islands Trust Territory",
                "Pakistan",
                "Palau",
                "Palestinian Territories",
                "Panama",
                "Panama Canal Zone",
                "Papua New Guinea",
                "Paraguay",
                "People's Democratic Republic of Yemen",
                "Peru",
                "Philippines",
                "Pitcairn Islands",
                "Poland",
                "Portugal",
                "Puerto Rico",
                "Qatar",
                "Réunion",
                "Romania",
                "Russia",
                "Rwanda",
                "Saint Barthélemy",
                "Saint Helena",
                "Saint Kitts and Nevis",
                "Saint Lucia",
                "Saint Martin",
                "Saint Pierre and Miquelon",
                "Saint Vincent and the Grenadines",
                "Samoa",
                "San Marino",
                "São Tomé and Príncipe",
                "Saudi Arabia",
                "Senegal",
                "Serbia",
                "Serbia and Montenegro",
                "Seychelles",
                "Sierra Leone",
                "Singapore",
                "Slovakia",
                "Slovenia",
                "Solomon Islands",
                "Somalia",
                "South Africa",
                "South Georgia and the South Sandwich Islands",
                "South Korea",
                "Spain",
                "Sri Lanka",
                "Sudan",
                "Suriname",
                "Svalbard and Jan Mayen",
                "Swaziland",
                "Sweden",
                "Switzerland",
                "Syria",
                "Taiwan",
                "Tajikistan",
                "Tanzania",
                "Thailand",
                "Timor-Leste",
                "Togo",
                "Tokelau",
                "Tonga",
                "Trinidad and Tobago",
                "Tristan da Cunha",
                "Tunisia",
                "Turkey",
                "Turkmenistan",
                "Turks and Caicos Islands",
                "Tuvalu",
                "U.S. Minor Outlying Islands",
                "U.S. Miscellaneous Pacific Islands",
                "U.S. Virgin Islands",
                "Uganda",
                "Ukraine",
                "United Arab Emirates",
                "United Kingdom",
                "United States",
                "Uruguay",
                "Uzbekistan",
                "Vanuatu",
                "Vatican City",
                "Venezuela",
                "Vietnam",
                "Wake Island",
                "Wallis and Futuna",
                "Western Sahara",
                "Yemen",
                "Zambia",
                "Zimbabwe"};

            return countries[(int)country];
        }
    }
}
